// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs4Ep13-FpxHgRJHDFQlhqf_4jk8e53po',
    appId: '1:726875352814:web:f60673d6b14fc705420dff',
    messagingSenderId: '726875352814',
    projectId: 'rokna-ffb4c',
    authDomain: 'rokna-ffb4c.firebaseapp.com',
    storageBucket: 'rokna-ffb4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdkvQcgFutrjtAOC1vUwPKrO7zy8lUQjQ',
    appId: '1:726875352814:android:5a51938d152c8625420dff',
    messagingSenderId: '726875352814',
    projectId: 'rokna-ffb4c',
    storageBucket: 'rokna-ffb4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKXqygT5xn06_F4iBlqHtI0-noue8q_yk',
    appId: '1:726875352814:ios:d2e11521c42566bf420dff',
    messagingSenderId: '726875352814',
    projectId: 'rokna-ffb4c',
    storageBucket: 'rokna-ffb4c.firebasestorage.app',
    iosBundleId: 'com.example.rokna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKXqygT5xn06_F4iBlqHtI0-noue8q_yk',
    appId: '1:726875352814:ios:d2e11521c42566bf420dff',
    messagingSenderId: '726875352814',
    projectId: 'rokna-ffb4c',
    storageBucket: 'rokna-ffb4c.firebasestorage.app',
    iosBundleId: 'com.example.rokna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs4Ep13-FpxHgRJHDFQlhqf_4jk8e53po',
    appId: '1:726875352814:web:a10f256d8e29bcaf420dff',
    messagingSenderId: '726875352814',
    projectId: 'rokna-ffb4c',
    authDomain: 'rokna-ffb4c.firebaseapp.com',
    storageBucket: 'rokna-ffb4c.firebasestorage.app',
  );
}
